version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/app
    networks:
      - my_network

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./wordpress:/app
    networks:
      - my_network

  data:
    image: mariadb
    container_name: data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
